### ISSUE TITLE
make the \command working, an option, some ppl don't like as default lol

### ISSUE THREAD

**Issue by Nseraf** [crazyman4865/EWDLC#14]

**Comment by RandomGuyJCI** [comment]
what?

**Comment by Nseraf** [comment]
<Nseraf> o/ g
<galarun> N
<galarun> N
<galarun> \o N
<Nseraf> oh yeah i forgot
<Nseraf> crazy added '
<Nseraf> as / in commands lol
<Nseraf> *\
<randompersonjci> what
<galarun> grr
<Nseraf> do \debug lol
<galarun> but why
<Nseraf> twas a request from krystoph
<Nseraf> bc ppl mistake the two
<randompersonjci> what
<galarun> hogwash

**Comment by Nseraf** [comment]
(the what has been solved!) :P 

<randompersonjci> w h a t ?????
galarun scythed a cube for 300 points.
<Nseraf> lol rando you know how you do /command ? now you can also do
<Nseraf> *\caommand
<Nseraf> does that answer the what? lol
Silmarillion101 earned 175 points
<randompersonjci> ohhhhh
<randompersonjci> */sc-info
r3 scythed a cube for 30 points.
<randompersonjci> *\sc-info
<Nseraf> yep
<randompersonjci> what
<Nseraf> without the * lol
<randompersonjci> ohhhhhh
<Nseraf> i just added the star so it wouldnt be a command :P
<randompersonjci> ohhhhhhhhhhhhhhhhh
<Nseraf> lol
