### ISSUE TITLE
Add amount of played years+days in profile

### ISSUE THREAD

**Issue by Nseraf** [crazyman4865/EWDLC#2]
Add amount of played years+days in profile, which increases every day, counting from Join day(date).
example:
![profile](https://user-images.githubusercontent.com/33002317/32142607-5eaae018-bca3-11e7-8920-da395c6e3316.jpg)

**Comment by Nseraf** [comment]
The red is only an indicator, not to be implemented, lol.

**Comment by crazyman4865** [comment]
How accurate would you want the time to be? Is [this](http://momentjs.com/docs/#/displaying/fromnow/) (the table) enough?

**Comment by annkri1** [comment]
perhaps have the largest gap in months? like you joined 22 months ago or 1 year and 10 months ago?

**Comment by Nseraf** [comment]
down to days is enough for me, personally but if others want mins or secs I wouldn't be 100% against it, lol.
