### ISSUE TITLE
Speed up sc-info

### ISSUE THREAD

**Issue by ChrisRaven** [crazyman4865/EWDLC#3]
Hi,

Currently you're invoking 4 AJAX requests in cascade to gather the required data. Since the requests aren't depending on each other, you can call them in parallel. I've done something pretty similar (using your code :) ) here: https://github.com/ChrisRaven/EWStats/blob/75c0262358c5c2f5435aca258690dc517320d34a/ewStats.user.js#L1569

**Comment by crazyman4865** [comment]
Thanks! I'll change it when I get the chance. 
Just a note for your code: instead of using a counter, consider using [$.when](https://api.jquery.com/jquery.when/). Then you can easily bind a success and fail handler to all the requests.

**Comment by ChrisRaven** [comment]
True that. I really should do more error handling not only here, but script-wide.
