### ISSUE TITLE
Sc-info still registers/shows stashed cubes

### ISSUE THREAD

**Issue by RandomGuyJCI** [crazyman4865/EWDLC#9]
Sometimes it even shows stashed cubes with NO WEIGHT.

![](https://puu.sh/yPpyl/2b14185937.png)

**Comment by annkri1** [comment]
Have seen this problem since right before christmas, also show stashed cubes with weight and the size command have the same trouble with showing more cubes than there is in cell. think it is worse in zfish cells than in ew cells because more stashed cells. Same trouble also with @kk`s script

**Comment by crazyman4865** [comment]
As I mentioned before, this is most likely an issue on EW's end. Probably the spawner updating the database too slow or there being some caching. I'm gonna ask around and see what's up.

**Comment by crazyman4865** [comment]
Chris confirmed there have been some changes, I'll get to work on changing my code to support them.
